### ISSUE TITLE
XML Schema location update

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra-spec#13]
Chapter 3.1.2 currently says "The XML schema is currently available in GitHub project fix-orchestra module repository2016. Upon promotion to draft standard, it will be made available at a URI consistent with its XML namespace."

Please create a URI for the draft standard and adapt spec accordingly. Does this also affect the root element containing "http://fixprotocol.io/2016/fixrepository"?

**Comment by donmendelson** [comment]
An XML namespace is a URI, which is theoretically only a globally unique name and not necessarily physical resource. (This confuses people because URIs have a protocol scheme for access; seems like a design error to me.) However, it is common practice to provide a page at a URL of the same name to serve the XML schema. (We did this for SBE at http://fixprotocol.io/2016/sbe/.)

An open question is whether we should keep the current namespace or update it to 2020 for the draft standard. I'm not sure how ISO or other standards bodies handle this a standard is in development for more than a year.

**Comment by kleihan** [comment]
I think we need to decouple the 2016 repository from orchestra and provide a separate URI, e.g. "http://fixprotocol.io/2020/orchestra". We may make changes in the future that should not impact the 2016 edition. My assumption is that they publication year is relevant, not the year that the development started.

My main issue was that RC5 states something that will happen with the change to DS. Now that we are changing to DS, the sentence no longer makes sense and has to be adapted. You are probably the better one of us to suggest a wording for this.

**Comment by donmendelson** [comment]
Namespaces and modules names updated in schema.
