### ISSUE TITLE
Refactoring Abbreviations

### ISSUE THREAD

**Issue by jimnup** [FIXTradingCommunity/fix-orchestra-spec#5]
The Abbreviations section of the Orchestra file was copied largely in tact over from the Unified Repository 2010 version.  In the 2010 we used the external phrases file for the term being abbreviated as opposed to including an attribute specifically for the term. This creates a layer of complexity that is unnecessary in practice. Also, the abbreviation section is used to build repository entries optionally, but its integration is not necessary for the working of an Orchestra repository. The last point made by Don is that there seems like there should be some connection between abbreviations and a controlled vocabulary. This discussion has led us to wonder if we should move abbreviations out of the core Orchestra file into its own related file as a separate entity?

**Comment by kleihan** [comment]
I believe it makes sense to see this as a separate entity, especially separate from the phrases file. Do we currently use abbreviations for anything else than FIXML? I see two aspects here. One is the abbreviation of single terms like "Inst" for "Instruction". And then there is the FIXML abbreviation for a FIX field name which is a concatenation of terms and where we have differences due to legacy naming, i.e. the same term may be abbreviated in different ways across multiple FIX fields, e.g. the term "Link" in LinkID (TradeLinkID) vs LnkID (ClOrdLinkID) vs omission (URLLink is abbreviated URL).

**Comment by donmendelson** [comment]
The consensus is to remove abbreviations from the Orchestra schema and manage them with a FIX vocabulary. See FIXTradingCommunity/fix-vocabulary
